### ISSUE TITLE
Interface from Go to Vizceral json format found inconsistencies

### ISSUE THREAD

**Issue by adrianco** [Netflix/vizceral-example#6]
I just built a first rough pass at a go package that maps the vizceral format
https://github.com/adrianco/go-vizceral

I ran into an issue where "metadata" is sometimes "streaming": true, and sometimes "streaming": 1 in the example file, which causes an error when marshal/unmarshal from go. I edited a copy of the example file to use "streaming": 1 everywhere, but it would be better to fix upstream wherever this data was generated.

**Comment by jasonwr** [comment]
@adrianco Sounds like Go is having issues with the marshalling and unmarshalling and this is a Go specific problem, rather than a Vizceral problem as the metadata field is optional. Simply omit it, and if this issue continues to be brought up again then a fix should be made. So far you're the only one who has complained about this.

**Comment by jrsquared** [comment]
@jasonwr It does point out inconsistencies with how the backend was generating the data. It is a very valid issue to point out.

@adrianco Thank you for pointing this out! I have since fixed the backend data generation to be consistent and updated the the sample json in f125a2f8c82b7d76062d12162a71b1e5caba3e3b.  Please let me know if you find anything else.

**Comment by jasonwr** [comment]
@jrsquared @adrianco My apologies! Good catch! I do know that your example data is valid JSON.

**Comment by adrianco** [comment]
Thanks for fixing this, I know that it is valid json, but when interfacing json to typed languages like Go it's much easier when the json types are consistent.
